name: Development
run-name: Compilation & Quality Checks

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
    branches:
      - '*'
      - '!develop'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build --workspace=@tomplum/react-git-log

      - name: Build Storybook
        run: npm run build-storybook --workspace=@tomplum/react-git-log-demo

      - name: ESLint Check
        run: npm run lint

      - name: Run Library Unit Tests
        env:
          TZ: UTC
        run: npm run test:unit:ci --workspace=@tomplum/react-git-log
        working-directory: packages/library

      - name: Run Demo Unit Tests
        env:
          TZ: UTC
        run: npm run test --workspace=@tomplum/react-git-log-demo
        working-directory: packages/demo

      - name: Run Integration Tests
        env:
          TZ: UTC
        run: npm run test:integration:ci --workspace=@tomplum/react-git-log
        working-directory: packages/library

      - name: SonarCloud Analysis
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: monitor --severity-threshold=high

      - name: Store Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: packages/library/coverage/lcov.info

