name: Development
run-name: Compilation & Quality Checks

on:
  push:
    branches: [develop]
  pull_request:
    types: [opened]
    branches:
      - '*'
      - '!develop'

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run build --workspace=@tomplum/react-git-log

  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm install
      - run: npm run build-storybook --workspace=@tomplum/react-git-log-demo

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run lint

  unit-tests-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run test:unit:ci --workspace=@tomplum/react-git-log
        working-directory: packages/library

  unit-tests-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run test --workspace=@tomplum/react-git-log-demo
        working-directory: packages/demo

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run test:integration:ci --workspace=@tomplum/react-git-log
        working-directory: packages/library

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [unit-tests-library, integration-tests]
    steps:
      - uses: actions/checkout@v4
      - name: SonarCloud Analysis
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  snyk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/library
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test --severity-threshold=high

  upload-coverage:
    runs-on: ubuntu-latest
    needs: unit-tests-library
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: packages/library/coverage/lcov.info