name: Development
run-name: Compilation & Quality Checks

on:
  pull_request:

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run build --workspace=@tomplum/react-git-log

  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run build-storybook --workspace=@tomplum/react-git-log-demo

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run lint

  docs:
    runs-on: ubuntu-latest
    needs: [build-library, lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run docs --workspace=@tomplum/react-git-log
        working-directory: packages/library

  unit-tests-library:
    runs-on: ubuntu-latest
    needs: [build-library, lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run test:unit:ci --workspace=@tomplum/react-git-log
        working-directory: packages/library
      - name: Store LCOV Info
        uses: actions/upload-artifact@v4
        with:
          name: line-coverage-info
          path: packages/library/coverage/lcov.info

  unit-tests-demo:
    runs-on: ubuntu-latest
    needs: [build-storybook, lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run test --workspace=@tomplum/react-git-log-demo
        working-directory: packages/demo

  integration-tests:
    runs-on: ubuntu-latest
    needs: [build-library, build-storybook, lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run test:integration:ci --workspace=@tomplum/react-git-log
        working-directory: packages/library

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [unit-tests-library, integration-tests, unit-tests-demo]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Download LCOV Info Artifact
        uses: actions/download-artifact@v4
        with:
          name: line-coverage-info
          path: packages/library/coverage
      - name: SonarCloud Analysis
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  snyk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/library
    needs: build-library
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: 'test'
          json: true
          args: --severity-threshold=high --all-projects